version: '3'

services:
  app:
    container_name: docker-kaypi-v2
    restart: always
    build: .
    image: kaypiadmin-v2
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongodb-v2
    image: mongo:5
    volumes:
      - ./localFolder:/data/db
    ports: 
      - '27018:27017'
     